from .AngularVelocityControlTab import AngularVelocityControlTab
from .DebugInfoTab import DebugInfoTab
from .RawDataGraphsTab import RawDataGraphsTab
from .RawDataTab import RawDataTab
from .SerialCommunicationTab import SerialCommunicationTab
from .StepperCalibrationTab import StepperCalibrationTab
